language: node_js
services:
- mongodb
- docker
sudo: required
env:
  secure: "D2odYxhrbyd4s6jm4MLBkoY/ELXFNLASayQ8hKZfRaqyBmMeisDKEuBrpkbvndOqrplDZ/jKG7nuA4I3qKsdWh5rMmN78VnOpjW75JqxwcqkaUVzQP4qimZm4ZiVDPWbJn6rQr//HMMZLaLROtVHEsZOHQGCgAgB1mZk8+p+vls="
before_deploy:
- heroku container:login
deploy:
  skip_cleanup: true
  provider: script
  script: yarn build && yarn deploy:push && yarn deploy:release
  on:
    branch: unity
