language: node_js
node_js:
- 6.2.1
services:
- mongodb
sudo: false
deploy:
  provider: heroku
  api_key:
    secure: PEHwBVlANBR4goE6j5MBNs3xs5XXNnLxYOhgrjaJBhlXCNKOZv2Lx/UTdu4URD51eLhBOO+LXclFdVVp3fDGRRSDQnKsAUwcpFgE8TIBCL3eLRXgfaVYxTLp9DFli7pP69gmgMhJe/6xxlKJMMD2KajSRjRDPOE4FgyFDAU4HdQ=
  app:
    master: gbptm-ui
    develop: gbptm-stage
